/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Contractify.ContractifyAPI.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;


public class CompanyRead {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("id")
    public Long id;

    public CompanyRead withId(Long id) {
        this.id = id;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("name")
    public String name;

    public CompanyRead withName(String name) {
        this.name = name;
        return this;
    }
    
    public CompanyRead(){}
}
