/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Contractify.ContractifyAPI.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;


public class ContractRenewal {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("automatic_renewal")
    public ContractAutomaticRenewal automaticRenewal;

    public ContractRenewal withAutomaticRenewal(ContractAutomaticRenewal automaticRenewal) {
        this.automaticRenewal = automaticRenewal;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("is_automatically_renewed")
    public Boolean isAutomaticallyRenewed;

    public ContractRenewal withIsAutomaticallyRenewed(Boolean isAutomaticallyRenewed) {
        this.isAutomaticallyRenewed = isAutomaticallyRenewed;
        return this;
    }
    
    public ContractRenewal(){}
}
