/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Contractify.ContractifyAPI.models.shared;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.time.LocalDate;


public class ContractTermination {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("is_terminable_at_any_time")
    public Boolean isTerminableAtAnyTime;

    public ContractTermination withIsTerminableAtAnyTime(Boolean isTerminableAtAnyTime) {
        this.isTerminableAtAnyTime = isTerminableAtAnyTime;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd")
    @JsonProperty("termination_date")
    public LocalDate terminationDate;

    public ContractTermination withTerminationDate(LocalDate terminationDate) {
        this.terminationDate = terminationDate;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("termination_duration")
    public String terminationDuration;

    public ContractTermination withTerminationDuration(String terminationDuration) {
        this.terminationDuration = terminationDuration;
        return this;
    }
    
    public ContractTermination(){}
}
