/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Contractify.ContractifyAPI.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;


public class ContractTypeNameRead {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("en")
    public String en;

    public ContractTypeNameRead withEn(String en) {
        this.en = en;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("fr")
    public String fr;

    public ContractTypeNameRead withFr(String fr) {
        this.fr = fr;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("nl")
    public String nl;

    public ContractTypeNameRead withNl(String nl) {
        this.nl = nl;
        return this;
    }
    
    public ContractTypeNameRead(){}
}
