/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Contractify.ContractifyAPI.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * ContractCollection - OK
 */

public class ContractCollection {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("data")
    public ContractRead[] data;

    public ContractCollection withData(ContractRead[] data) {
        this.data = data;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("meta")
    public Pagination meta;

    public ContractCollection withMeta(Pagination meta) {
        this.meta = meta;
        return this;
    }
    
    public ContractCollection(){}
}
