/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Contractify.ContractifyAPI.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;


public class ContractAutomaticRenewal {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("number_of_renewals")
    public Long numberOfRenewals;

    public ContractAutomaticRenewal withNumberOfRenewals(Long numberOfRenewals) {
        this.numberOfRenewals = numberOfRenewals;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("renewal_period")
    public String renewalPeriod;

    public ContractAutomaticRenewal withRenewalPeriod(String renewalPeriod) {
        this.renewalPeriod = renewalPeriod;
        return this;
    }
    
    public ContractAutomaticRenewal(){}
}
