/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Contractify.ContractifyAPI.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

public enum ContractPhase {
    TENDER("tender"),
    ONGOING("ongoing"),
    IN_TERMINATION("in_termination"),
    ENDED("ended"),
    IN_REVIEW("in_review");

    @JsonValue
    public final String value;

    private ContractPhase(String value) {
        this.value = value;
    }
}
