/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Contractify.ContractifyAPI.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;


public class CustomFieldValueRead {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("custom_field_id")
    public Long customFieldId;

    public CustomFieldValueRead withCustomFieldId(Long customFieldId) {
        this.customFieldId = customFieldId;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("id")
    public Long id;

    public CustomFieldValueRead withId(Long id) {
        this.id = id;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("value")
    public Object value;

    public CustomFieldValueRead withValue(Object value) {
        this.value = value;
        return this;
    }
    
    public CustomFieldValueRead(){}
}
