/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Contractify.ContractifyAPI.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;


public class CustomFieldValueWrite {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("custom_field_id")
    public Long customFieldId;

    public CustomFieldValueWrite withCustomFieldId(Long customFieldId) {
        this.customFieldId = customFieldId;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("value")
    public Object value;

    public CustomFieldValueWrite withValue(Object value) {
        this.value = value;
        return this;
    }
    
    public CustomFieldValueWrite(){}
}
