/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Contractify.ContractifyAPI.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * CustomFieldCollection - OK
 */

public class CustomFieldCollection {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("data")
    public CustomFieldRead[] data;

    public CustomFieldCollection withData(CustomFieldRead[] data) {
        this.data = data;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("meta")
    public Pagination meta;

    public CustomFieldCollection withMeta(Pagination meta) {
        this.meta = meta;
        return this;
    }
    
    public CustomFieldCollection(){}
}
