/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Contractify.ContractifyAPI.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;


public class DepartmentWrite {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("name")
    public String name;

    public DepartmentWrite withName(String name) {
        this.name = name;
        return this;
    }
    
    public DepartmentWrite(){}
}
