/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Contractify.ContractifyAPI.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * DepartmentCollection - OK
 */

public class DepartmentCollection {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("data")
    public DepartmentRead[] data;

    public DepartmentCollection withData(DepartmentRead[] data) {
        this.data = data;
        return this;
    }
    
    public DepartmentCollection(){}
}
