/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Contractify.ContractifyAPI.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;


public class DocumentVersionRead {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("created_at")
    public String createdAt;

    public DocumentVersionRead withCreatedAt(String createdAt) {
        this.createdAt = createdAt;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("detected_lanugage")
    public String detectedLanugage;

    public DocumentVersionRead withDetectedLanugage(String detectedLanugage) {
        this.detectedLanugage = detectedLanugage;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("download_url")
    public String downloadUrl;

    public DocumentVersionRead withDownloadUrl(String downloadUrl) {
        this.downloadUrl = downloadUrl;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("file_size")
    public Long fileSize;

    public DocumentVersionRead withFileSize(Long fileSize) {
        this.fileSize = fileSize;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("file_type")
    public String fileType;

    public DocumentVersionRead withFileType(String fileType) {
        this.fileType = fileType;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("mime_type")
    public String mimeType;

    public DocumentVersionRead withMimeType(String mimeType) {
        this.mimeType = mimeType;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("name")
    public String name;

    public DocumentVersionRead withName(String name) {
        this.name = name;
        return this;
    }
    
    public DocumentVersionRead(){}
}
