/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Contractify.ContractifyAPI.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;


public class DocumentWrite {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("contracts")
    public Long[] contracts;

    public DocumentWrite withContracts(Long[] contracts) {
        this.contracts = contracts;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("custom_field_values")
    public CustomFieldValueWrite[] customFieldValues;

    public DocumentWrite withCustomFieldValues(CustomFieldValueWrite[] customFieldValues) {
        this.customFieldValues = customFieldValues;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("description")
    public String description;

    public DocumentWrite withDescription(String description) {
        this.description = description;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("dossiers")
    public Long[] dossiers;

    public DocumentWrite withDossiers(Long[] dossiers) {
        this.dossiers = dossiers;
        return this;
    }
    
    @JsonProperty("name")
    public String name;

    public DocumentWrite withName(String name) {
        this.name = name;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("owner_id")
    public Long ownerId;

    public DocumentWrite withOwnerId(Long ownerId) {
        this.ownerId = ownerId;
        return this;
    }
    
    public DocumentWrite(@JsonProperty("name") String name) {
        this.name = name;
  }
}
