/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Contractify.ContractifyAPI.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * DocumentCollection - OK
 */

public class DocumentCollection {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("data")
    public DocumentRead[] data;

    public DocumentCollection withData(DocumentRead[] data) {
        this.data = data;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("meta")
    public Pagination meta;

    public DocumentCollection withMeta(Pagination meta) {
        this.meta = meta;
        return this;
    }
    
    public DocumentCollection(){}
}
