/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Contractify.ContractifyAPI.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * DossierCollection - OK
 */

public class DossierCollection {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("data")
    public DossierRead[] data;

    public DossierCollection withData(DossierRead[] data) {
        this.data = data;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("meta")
    public Pagination meta;

    public DossierCollection withMeta(Pagination meta) {
        this.meta = meta;
        return this;
    }
    
    public DossierCollection(){}
}
