/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Contractify.ContractifyAPI.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * LegalEntityCollection - OK
 */

public class LegalEntityCollection {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("data")
    public LegalEntityRead[] data;

    public LegalEntityCollection withData(LegalEntityRead[] data) {
        this.data = data;
        return this;
    }
    
    public LegalEntityCollection(){}
}
