/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Contractify.ContractifyAPI.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;


public class LegalEntityRead {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("bus")
    public String bus;

    public LegalEntityRead withBus(String bus) {
        this.bus = bus;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("city")
    public String city;

    public LegalEntityRead withCity(String city) {
        this.city = city;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("country")
    public String country;

    public LegalEntityRead withCountry(String country) {
        this.country = country;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("id")
    public Long id;

    public LegalEntityRead withId(Long id) {
        this.id = id;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("name")
    public String name;

    public LegalEntityRead withName(String name) {
        this.name = name;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("street")
    public String street;

    public LegalEntityRead withStreet(String street) {
        this.street = street;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("vat")
    public String vat;

    public LegalEntityRead withVat(String vat) {
        this.vat = vat;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("zip")
    public String zip;

    public LegalEntityRead withZip(String zip) {
        this.zip = zip;
        return this;
    }
    
    public LegalEntityRead(){}
}
