/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Contractify.ContractifyAPI.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * OfficeCollection - OK
 */

public class OfficeCollection {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("data")
    public OfficeRead[] data;

    public OfficeCollection withData(OfficeRead[] data) {
        this.data = data;
        return this;
    }
    
    public OfficeCollection(){}
}
