/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Contractify.ContractifyAPI.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;


public class OfficeRead {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("bus")
    public String bus;

    public OfficeRead withBus(String bus) {
        this.bus = bus;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("city")
    public String city;

    public OfficeRead withCity(String city) {
        this.city = city;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("contact_person")
    public String contactPerson;

    public OfficeRead withContactPerson(String contactPerson) {
        this.contactPerson = contactPerson;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("country")
    public String country;

    public OfficeRead withCountry(String country) {
        this.country = country;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("email")
    public String email;

    public OfficeRead withEmail(String email) {
        this.email = email;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("id")
    public Long id;

    public OfficeRead withId(Long id) {
        this.id = id;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("name")
    public String name;

    public OfficeRead withName(String name) {
        this.name = name;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("number_identity")
    public String numberIdentity;

    public OfficeRead withNumberIdentity(String numberIdentity) {
        this.numberIdentity = numberIdentity;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("permalink")
    public String permalink;

    public OfficeRead withPermalink(String permalink) {
        this.permalink = permalink;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("phone")
    public String phone;

    public OfficeRead withPhone(String phone) {
        this.phone = phone;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("street")
    public String street;

    public OfficeRead withStreet(String street) {
        this.street = street;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("zip")
    public String zip;

    public OfficeRead withZip(String zip) {
        this.zip = zip;
        return this;
    }
    
    public OfficeRead(){}
}
