/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Contractify.ContractifyAPI.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * RelationCollection - OK
 */

public class RelationCollection {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("data")
    public RelationRead[] data;

    public RelationCollection withData(RelationRead[] data) {
        this.data = data;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("meta")
    public Pagination meta;

    public RelationCollection withMeta(Pagination meta) {
        this.meta = meta;
        return this;
    }
    
    public RelationCollection(){}
}
