/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Contractify.ContractifyAPI.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;


public class RelationWrite {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("address")
    public Address address;

    public RelationWrite withAddress(Address address) {
        this.address = address;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("email")
    public String email;

    public RelationWrite withEmail(String email) {
        this.email = email;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("fax")
    public String fax;

    public RelationWrite withFax(String fax) {
        this.fax = fax;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("mobile_phone")
    public String mobilePhone;

    public RelationWrite withMobilePhone(String mobilePhone) {
        this.mobilePhone = mobilePhone;
        return this;
    }
    
    @JsonProperty("name")
    public String name;

    public RelationWrite withName(String name) {
        this.name = name;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("phone")
    public String phone;

    public RelationWrite withPhone(String phone) {
        this.phone = phone;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("reference")
    public String reference;

    public RelationWrite withReference(String reference) {
        this.reference = reference;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("vat")
    public String vat;

    public RelationWrite withVat(String vat) {
        this.vat = vat;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("website")
    public String website;

    public RelationWrite withWebsite(String website) {
        this.website = website;
        return this;
    }
    
    public RelationWrite(@JsonProperty("name") String name) {
        this.name = name;
  }
}
