/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Contractify.ContractifyAPI.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * TaskWriteDueDateDependsOn - Will only be accepted if you pass a `contract_id`
 */
public enum TaskWriteDueDateDependsOn {
    TERMINATION_DATE("termination_date"),
    END_DATE("end_date"),
    START_DATE("start_date");

    @JsonValue
    public final String value;

    private TaskWriteDueDateDependsOn(String value) {
        this.value = value;
    }
}
