/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Contractify.ContractifyAPI.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

public enum TaskWriteStatus {
    ACCOMPLISHED("accomplished"),
    NOT_ACCOMPLISHED("not_accomplished"),
    IN_PROGRESS("in_progress");

    @JsonValue
    public final String value;

    private TaskWriteStatus(String value) {
        this.value = value;
    }
}
