/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Contractify.ContractifyAPI.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * TaskCollection - OK
 */

public class TaskCollection {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("data")
    public TaskRead[] data;

    public TaskCollection withData(TaskRead[] data) {
        this.data = data;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("meta")
    public Pagination meta;

    public TaskCollection withMeta(Pagination meta) {
        this.meta = meta;
        return this;
    }
    
    public TaskCollection(){}
}
