/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Contractify.ContractifyAPI.models.shared;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.time.LocalDate;


public class TaskUpdate {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("description")
    public String description;

    public TaskUpdate withDescription(String description) {
        this.description = description;
        return this;
    }
    
    /**
     * Will be overwritten if `due_date_depends_on` and `due_date_interval` are passed
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd")
    @JsonProperty("due_date")
    public LocalDate dueDate;

    public TaskUpdate withDueDate(LocalDate dueDate) {
        this.dueDate = dueDate;
        return this;
    }
    
    /**
     * Will only be accepted if you pass a `contract_id`
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("due_date_depends_on")
    public TaskUpdateDueDateDependsOn dueDateDependsOn;

    public TaskUpdate withDueDateDependsOn(TaskUpdateDueDateDependsOn dueDateDependsOn) {
        this.dueDateDependsOn = dueDateDependsOn;
        return this;
    }
    
    /**
     * Will only be accepted if you pass a `contract_id`
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("due_date_interval")
    public String dueDateInterval;

    public TaskUpdate withDueDateInterval(String dueDateInterval) {
        this.dueDateInterval = dueDateInterval;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("owner_id")
    public Long ownerId;

    public TaskUpdate withOwnerId(Long ownerId) {
        this.ownerId = ownerId;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("reminder_duration")
    public String reminderDuration;

    public TaskUpdate withReminderDuration(String reminderDuration) {
        this.reminderDuration = reminderDuration;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("repetition_interval")
    public String repetitionInterval;

    public TaskUpdate withRepetitionInterval(String repetitionInterval) {
        this.repetitionInterval = repetitionInterval;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("status")
    public TaskUpdateStatus status;

    public TaskUpdate withStatus(TaskUpdateStatus status) {
        this.status = status;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("title")
    public String title;

    public TaskUpdate withTitle(String title) {
        this.title = title;
        return this;
    }
    
    public TaskUpdate(){}
}
