/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Contractify.ContractifyAPI.models.shared;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.time.LocalDate;


public class TaskWrite {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("contract_id")
    public Long contractId;

    public TaskWrite withContractId(Long contractId) {
        this.contractId = contractId;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("description")
    public String description;

    public TaskWrite withDescription(String description) {
        this.description = description;
        return this;
    }
    
    /**
     * Will be overwritten if `due_date_depends_on` and `due_date_interval` are passed
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd")
    @JsonProperty("due_date")
    public LocalDate dueDate;

    public TaskWrite withDueDate(LocalDate dueDate) {
        this.dueDate = dueDate;
        return this;
    }
    
    /**
     * Will only be accepted if you pass a `contract_id`
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("due_date_depends_on")
    public TaskWriteDueDateDependsOn dueDateDependsOn;

    public TaskWrite withDueDateDependsOn(TaskWriteDueDateDependsOn dueDateDependsOn) {
        this.dueDateDependsOn = dueDateDependsOn;
        return this;
    }
    
    /**
     * Will only be accepted if you pass a `contract_id`
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("due_date_interval")
    public String dueDateInterval;

    public TaskWrite withDueDateInterval(String dueDateInterval) {
        this.dueDateInterval = dueDateInterval;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("owner_id")
    public Long ownerId;

    public TaskWrite withOwnerId(Long ownerId) {
        this.ownerId = ownerId;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("reminder_duration")
    public String reminderDuration;

    public TaskWrite withReminderDuration(String reminderDuration) {
        this.reminderDuration = reminderDuration;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("repetition_interval")
    public String repetitionInterval;

    public TaskWrite withRepetitionInterval(String repetitionInterval) {
        this.repetitionInterval = repetitionInterval;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("status")
    public TaskWriteStatus status;

    public TaskWrite withStatus(TaskWriteStatus status) {
        this.status = status;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("title")
    public String title;

    public TaskWrite withTitle(String title) {
        this.title = title;
        return this;
    }
    
    public TaskWrite(){}
}
