/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Contractify.ContractifyAPI.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * UserCollection - OK
 */

public class UserCollection {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("data")
    public UserRead[] data;

    public UserCollection withData(UserRead[] data) {
        this.data = data;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("meta")
    public Pagination meta;

    public UserCollection withMeta(Pagination meta) {
        this.meta = meta;
        return this;
    }
    
    public UserCollection(){}
}
