/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Contractify.ContractifyAPI.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

public enum UserReadRole {
    ADMIN("admin"),
    MANAGER("manager"),
    USER("user");

    @JsonValue
    public final String value;

    private UserReadRole(String value) {
        this.value = value;
    }
}
