/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Contractify.ContractifyAPI.models.operations;

import Contractify.ContractifyAPI.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;


public class CreateOfficeRequest {
    @SpeakeasyMetadata("request:mediaType=application/json")
    public Contractify.ContractifyAPI.models.shared.OfficeWrite officeWrite;

    public CreateOfficeRequest withOfficeWrite(Contractify.ContractifyAPI.models.shared.OfficeWrite officeWrite) {
        this.officeWrite = officeWrite;
        return this;
    }
    
    /**
     * Id of the company
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=company")
    public Long company;

    public CreateOfficeRequest withCompany(Long company) {
        this.company = company;
        return this;
    }
    
    public CreateOfficeRequest(@JsonProperty("company") Long company) {
        this.company = company;
  }
}
