/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Contractify.ContractifyAPI.models.operations;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * CreateContract422ApplicationJSON - Invalid data posted
 */

public class CreateContract422ApplicationJSON {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("errors")
    public CreateContract422ApplicationJSONErrors[] errors;

    public CreateContract422ApplicationJSON withErrors(CreateContract422ApplicationJSONErrors[] errors) {
        this.errors = errors;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("message")
    public String message;

    public CreateContract422ApplicationJSON withMessage(String message) {
        this.message = message;
        return this;
    }
    
    public CreateContract422ApplicationJSON(){}
}
