/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Contractify.ContractifyAPI.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class CreateRelationResponse {
    
    public String contentType;

    public CreateRelationResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public CreateRelationResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public CreateRelationResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * Created
     */
    
    public CreateRelation201ApplicationJSON createRelation201ApplicationJSONObject;

    public CreateRelationResponse withCreateRelation201ApplicationJSONObject(CreateRelation201ApplicationJSON createRelation201ApplicationJSONObject) {
        this.createRelation201ApplicationJSONObject = createRelation201ApplicationJSONObject;
        return this;
    }
    
    /**
     * Unauthenticated
     */
    
    public CreateRelation401ApplicationJSON createRelation401ApplicationJSONObject;

    public CreateRelationResponse withCreateRelation401ApplicationJSONObject(CreateRelation401ApplicationJSON createRelation401ApplicationJSONObject) {
        this.createRelation401ApplicationJSONObject = createRelation401ApplicationJSONObject;
        return this;
    }
    
    /**
     * Forbidden
     */
    
    public CreateRelation403ApplicationJSON createRelation403ApplicationJSONObject;

    public CreateRelationResponse withCreateRelation403ApplicationJSONObject(CreateRelation403ApplicationJSON createRelation403ApplicationJSONObject) {
        this.createRelation403ApplicationJSONObject = createRelation403ApplicationJSONObject;
        return this;
    }
    
    /**
     * Invalid data posted
     */
    
    public CreateRelation422ApplicationJSON createRelation422ApplicationJSONObject;

    public CreateRelationResponse withCreateRelation422ApplicationJSONObject(CreateRelation422ApplicationJSON createRelation422ApplicationJSONObject) {
        this.createRelation422ApplicationJSONObject = createRelation422ApplicationJSONObject;
        return this;
    }
    
    public CreateRelationResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
