/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Contractify.ContractifyAPI.models.operations;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * CreateRelation201ApplicationJSON - Created
 */

public class CreateRelation201ApplicationJSON {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("data")
    public Contractify.ContractifyAPI.models.shared.RelationRead data;

    public CreateRelation201ApplicationJSON withData(Contractify.ContractifyAPI.models.shared.RelationRead data) {
        this.data = data;
        return this;
    }
    
    public CreateRelation201ApplicationJSON(){}
}
