/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Contractify.ContractifyAPI.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class CreateContractResponse {
    
    public String contentType;

    public CreateContractResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public CreateContractResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public CreateContractResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * Created
     */
    
    public CreateContract201ApplicationJSON createContract201ApplicationJSONObject;

    public CreateContractResponse withCreateContract201ApplicationJSONObject(CreateContract201ApplicationJSON createContract201ApplicationJSONObject) {
        this.createContract201ApplicationJSONObject = createContract201ApplicationJSONObject;
        return this;
    }
    
    /**
     * Unauthenticated
     */
    
    public CreateContract401ApplicationJSON createContract401ApplicationJSONObject;

    public CreateContractResponse withCreateContract401ApplicationJSONObject(CreateContract401ApplicationJSON createContract401ApplicationJSONObject) {
        this.createContract401ApplicationJSONObject = createContract401ApplicationJSONObject;
        return this;
    }
    
    /**
     * Forbidden
     */
    
    public CreateContract403ApplicationJSON createContract403ApplicationJSONObject;

    public CreateContractResponse withCreateContract403ApplicationJSONObject(CreateContract403ApplicationJSON createContract403ApplicationJSONObject) {
        this.createContract403ApplicationJSONObject = createContract403ApplicationJSONObject;
        return this;
    }
    
    /**
     * Invalid data posted
     */
    
    public CreateContract422ApplicationJSON createContract422ApplicationJSONObject;

    public CreateContractResponse withCreateContract422ApplicationJSONObject(CreateContract422ApplicationJSON createContract422ApplicationJSONObject) {
        this.createContract422ApplicationJSONObject = createContract422ApplicationJSONObject;
        return this;
    }
    
    public CreateContractResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
