/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Contractify.ContractifyAPI.models.operations;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * CreateOffice201ApplicationJSON - Created
 */

public class CreateOffice201ApplicationJSON {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("data")
    public Contractify.ContractifyAPI.models.shared.OfficeRead data;

    public CreateOffice201ApplicationJSON withData(Contractify.ContractifyAPI.models.shared.OfficeRead data) {
        this.data = data;
        return this;
    }
    
    public CreateOffice201ApplicationJSON(){}
}
