/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Contractify.ContractifyAPI.models.operations;

import Contractify.ContractifyAPI.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;


public class CreateRelationRequest {
    @SpeakeasyMetadata("request:mediaType=application/json")
    public Contractify.ContractifyAPI.models.shared.RelationWrite relationWrite;

    public CreateRelationRequest withRelationWrite(Contractify.ContractifyAPI.models.shared.RelationWrite relationWrite) {
        this.relationWrite = relationWrite;
        return this;
    }
    
    /**
     * Id of the company
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=company")
    public Long company;

    public CreateRelationRequest withCompany(Long company) {
        this.company = company;
        return this;
    }
    
    public CreateRelationRequest(@JsonProperty("company") Long company) {
        this.company = company;
  }
}
