/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Contractify.ContractifyAPI.models.operations;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * CreateOffice422ApplicationJSON - Invalid data posted
 */

public class CreateOffice422ApplicationJSON {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("errors")
    public CreateOffice422ApplicationJSONErrors[] errors;

    public CreateOffice422ApplicationJSON withErrors(CreateOffice422ApplicationJSONErrors[] errors) {
        this.errors = errors;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("message")
    public String message;

    public CreateOffice422ApplicationJSON withMessage(String message) {
        this.message = message;
        return this;
    }
    
    public CreateOffice422ApplicationJSON(){}
}
