/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Contractify.ContractifyAPI.models.operations;

import Contractify.ContractifyAPI.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;


public class CreateContractRequest {
    @SpeakeasyMetadata("request:mediaType=application/json")
    public Contractify.ContractifyAPI.models.shared.ContractWrite contractWrite;

    public CreateContractRequest withContractWrite(Contractify.ContractifyAPI.models.shared.ContractWrite contractWrite) {
        this.contractWrite = contractWrite;
        return this;
    }
    
    /**
     * Id of the company
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=company")
    public Long company;

    public CreateContractRequest withCompany(Long company) {
        this.company = company;
        return this;
    }
    
    public CreateContractRequest(@JsonProperty("company") Long company) {
        this.company = company;
  }
}
