/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Contractify.ContractifyAPI.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class CreateDepartmentResponse {
    
    public String contentType;

    public CreateDepartmentResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public CreateDepartmentResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public CreateDepartmentResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * Created
     */
    
    public CreateDepartment201ApplicationJSON createDepartment201ApplicationJSONObject;

    public CreateDepartmentResponse withCreateDepartment201ApplicationJSONObject(CreateDepartment201ApplicationJSON createDepartment201ApplicationJSONObject) {
        this.createDepartment201ApplicationJSONObject = createDepartment201ApplicationJSONObject;
        return this;
    }
    
    /**
     * Unauthenticated
     */
    
    public CreateDepartment401ApplicationJSON createDepartment401ApplicationJSONObject;

    public CreateDepartmentResponse withCreateDepartment401ApplicationJSONObject(CreateDepartment401ApplicationJSON createDepartment401ApplicationJSONObject) {
        this.createDepartment401ApplicationJSONObject = createDepartment401ApplicationJSONObject;
        return this;
    }
    
    /**
     * Forbidden
     */
    
    public CreateDepartment403ApplicationJSON createDepartment403ApplicationJSONObject;

    public CreateDepartmentResponse withCreateDepartment403ApplicationJSONObject(CreateDepartment403ApplicationJSON createDepartment403ApplicationJSONObject) {
        this.createDepartment403ApplicationJSONObject = createDepartment403ApplicationJSONObject;
        return this;
    }
    
    /**
     * Invalid data posted
     */
    
    public CreateDepartment422ApplicationJSON createDepartment422ApplicationJSONObject;

    public CreateDepartmentResponse withCreateDepartment422ApplicationJSONObject(CreateDepartment422ApplicationJSON createDepartment422ApplicationJSONObject) {
        this.createDepartment422ApplicationJSONObject = createDepartment422ApplicationJSONObject;
        return this;
    }
    
    public CreateDepartmentResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
