/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Contractify.ContractifyAPI.models.operations;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * CreateContract201ApplicationJSON - Created
 */

public class CreateContract201ApplicationJSON {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("data")
    public Contractify.ContractifyAPI.models.shared.ContractRead data;

    public CreateContract201ApplicationJSON withData(Contractify.ContractifyAPI.models.shared.ContractRead data) {
        this.data = data;
        return this;
    }
    
    public CreateContract201ApplicationJSON(){}
}
