/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Contractify.ContractifyAPI.models.operations;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * CreateDepartment201ApplicationJSON - Created
 */

public class CreateDepartment201ApplicationJSON {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("data")
    public Contractify.ContractifyAPI.models.shared.DepartmentRead data;

    public CreateDepartment201ApplicationJSON withData(Contractify.ContractifyAPI.models.shared.DepartmentRead data) {
        this.data = data;
        return this;
    }
    
    public CreateDepartment201ApplicationJSON(){}
}
