/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Contractify.ContractifyAPI.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class CreateOfficeResponse {
    
    public String contentType;

    public CreateOfficeResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public CreateOfficeResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public CreateOfficeResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * Created
     */
    
    public CreateOffice201ApplicationJSON createOffice201ApplicationJSONObject;

    public CreateOfficeResponse withCreateOffice201ApplicationJSONObject(CreateOffice201ApplicationJSON createOffice201ApplicationJSONObject) {
        this.createOffice201ApplicationJSONObject = createOffice201ApplicationJSONObject;
        return this;
    }
    
    /**
     * Unauthenticated
     */
    
    public CreateOffice401ApplicationJSON createOffice401ApplicationJSONObject;

    public CreateOfficeResponse withCreateOffice401ApplicationJSONObject(CreateOffice401ApplicationJSON createOffice401ApplicationJSONObject) {
        this.createOffice401ApplicationJSONObject = createOffice401ApplicationJSONObject;
        return this;
    }
    
    /**
     * Forbidden
     */
    
    public CreateOffice403ApplicationJSON createOffice403ApplicationJSONObject;

    public CreateOfficeResponse withCreateOffice403ApplicationJSONObject(CreateOffice403ApplicationJSON createOffice403ApplicationJSONObject) {
        this.createOffice403ApplicationJSONObject = createOffice403ApplicationJSONObject;
        return this;
    }
    
    /**
     * Invalid data posted
     */
    
    public CreateOffice422ApplicationJSON createOffice422ApplicationJSONObject;

    public CreateOfficeResponse withCreateOffice422ApplicationJSONObject(CreateOffice422ApplicationJSON createOffice422ApplicationJSONObject) {
        this.createOffice422ApplicationJSONObject = createOffice422ApplicationJSONObject;
        return this;
    }
    
    public CreateOfficeResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
