/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Contractify.ContractifyAPI.models.operations;

import Contractify.ContractifyAPI.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;


public class CreateDepartmentRequest {
    @SpeakeasyMetadata("request:mediaType=application/json")
    public Contractify.ContractifyAPI.models.shared.DepartmentWrite departmentWrite;

    public CreateDepartmentRequest withDepartmentWrite(Contractify.ContractifyAPI.models.shared.DepartmentWrite departmentWrite) {
        this.departmentWrite = departmentWrite;
        return this;
    }
    
    /**
     * Id of the company
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=company")
    public Long company;

    public CreateDepartmentRequest withCompany(Long company) {
        this.company = company;
        return this;
    }
    
    public CreateDepartmentRequest(@JsonProperty("company") Long company) {
        this.company = company;
  }
}
