/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Contractify.ContractifyAPI.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class CreateTaskResponse {
    
    public String contentType;

    public CreateTaskResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public CreateTaskResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public CreateTaskResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * OK
     */
    
    public CreateTask200ApplicationJSON createTask200ApplicationJSONObject;

    public CreateTaskResponse withCreateTask200ApplicationJSONObject(CreateTask200ApplicationJSON createTask200ApplicationJSONObject) {
        this.createTask200ApplicationJSONObject = createTask200ApplicationJSONObject;
        return this;
    }
    
    /**
     * Unauthenticated
     */
    
    public CreateTask401ApplicationJSON createTask401ApplicationJSONObject;

    public CreateTaskResponse withCreateTask401ApplicationJSONObject(CreateTask401ApplicationJSON createTask401ApplicationJSONObject) {
        this.createTask401ApplicationJSONObject = createTask401ApplicationJSONObject;
        return this;
    }
    
    /**
     * Forbidden
     */
    
    public CreateTask403ApplicationJSON createTask403ApplicationJSONObject;

    public CreateTaskResponse withCreateTask403ApplicationJSONObject(CreateTask403ApplicationJSON createTask403ApplicationJSONObject) {
        this.createTask403ApplicationJSONObject = createTask403ApplicationJSONObject;
        return this;
    }
    
    /**
     * Invalid data posted
     */
    
    public CreateTask422ApplicationJSON createTask422ApplicationJSONObject;

    public CreateTaskResponse withCreateTask422ApplicationJSONObject(CreateTask422ApplicationJSON createTask422ApplicationJSONObject) {
        this.createTask422ApplicationJSONObject = createTask422ApplicationJSONObject;
        return this;
    }
    
    public CreateTaskResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
