/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Contractify.ContractifyAPI.models.operations;

import Contractify.ContractifyAPI.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;


public class CreateTaskRequest {
    @SpeakeasyMetadata("request:mediaType=application/json")
    public Contractify.ContractifyAPI.models.shared.TaskWrite taskWrite;

    public CreateTaskRequest withTaskWrite(Contractify.ContractifyAPI.models.shared.TaskWrite taskWrite) {
        this.taskWrite = taskWrite;
        return this;
    }
    
    /**
     * Id of the company
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=company")
    public Long company;

    public CreateTaskRequest withCompany(Long company) {
        this.company = company;
        return this;
    }
    
    public CreateTaskRequest(@JsonProperty("company") Long company) {
        this.company = company;
  }
}
