/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Contractify.ContractifyAPI.models.operations;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * CurrentUser200ApplicationJSON - OK
 */

public class CurrentUser200ApplicationJSON {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("data")
    public Contractify.ContractifyAPI.models.shared.UserCurrent data;

    public CurrentUser200ApplicationJSON withData(Contractify.ContractifyAPI.models.shared.UserCurrent data) {
        this.data = data;
        return this;
    }
    
    public CurrentUser200ApplicationJSON(){}
}
