/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Contractify.ContractifyAPI.models.operations;

import Contractify.ContractifyAPI.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;


public class DeleteDepartmentRequest {
    /**
     * Id of the company
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=company")
    public Long company;

    public DeleteDepartmentRequest withCompany(Long company) {
        this.company = company;
        return this;
    }
    
    /**
     * Id of the department
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=department")
    public Long department;

    public DeleteDepartmentRequest withDepartment(Long department) {
        this.department = department;
        return this;
    }
    
    public DeleteDepartmentRequest(@JsonProperty("company") Long company, @JsonProperty("department") Long department) {
        this.company = company;
        this.department = department;
  }
}
