/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Contractify.ContractifyAPI.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class DeleteDocumentResponse {
    
    public String contentType;

    public DeleteDocumentResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public DeleteDocumentResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public DeleteDocumentResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * Unauthenticated
     */
    
    public DeleteDocument401ApplicationJSON deleteDocument401ApplicationJSONObject;

    public DeleteDocumentResponse withDeleteDocument401ApplicationJSONObject(DeleteDocument401ApplicationJSON deleteDocument401ApplicationJSONObject) {
        this.deleteDocument401ApplicationJSONObject = deleteDocument401ApplicationJSONObject;
        return this;
    }
    
    /**
     * Forbidden
     */
    
    public DeleteDocument403ApplicationJSON deleteDocument403ApplicationJSONObject;

    public DeleteDocumentResponse withDeleteDocument403ApplicationJSONObject(DeleteDocument403ApplicationJSON deleteDocument403ApplicationJSONObject) {
        this.deleteDocument403ApplicationJSONObject = deleteDocument403ApplicationJSONObject;
        return this;
    }
    
    /**
     * Not Found
     */
    
    public DeleteDocument404ApplicationJSON deleteDocument404ApplicationJSONObject;

    public DeleteDocumentResponse withDeleteDocument404ApplicationJSONObject(DeleteDocument404ApplicationJSON deleteDocument404ApplicationJSONObject) {
        this.deleteDocument404ApplicationJSONObject = deleteDocument404ApplicationJSONObject;
        return this;
    }
    
    /**
     * Invalid data posted
     */
    
    public DeleteDocument422ApplicationJSON deleteDocument422ApplicationJSONObject;

    public DeleteDocumentResponse withDeleteDocument422ApplicationJSONObject(DeleteDocument422ApplicationJSON deleteDocument422ApplicationJSONObject) {
        this.deleteDocument422ApplicationJSONObject = deleteDocument422ApplicationJSONObject;
        return this;
    }
    
    public DeleteDocumentResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
