/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Contractify.ContractifyAPI.models.operations;

import Contractify.ContractifyAPI.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;


public class DeleteOfficeRequest {
    /**
     * Id of the company
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=company")
    public Long company;

    public DeleteOfficeRequest withCompany(Long company) {
        this.company = company;
        return this;
    }
    
    /**
     * Id of the office
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=office")
    public Long office;

    public DeleteOfficeRequest withOffice(Long office) {
        this.office = office;
        return this;
    }
    
    public DeleteOfficeRequest(@JsonProperty("company") Long company, @JsonProperty("office") Long office) {
        this.company = company;
        this.office = office;
  }
}
