/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Contractify.ContractifyAPI.models.operations;

import Contractify.ContractifyAPI.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;


public class DeleteContractRequest {
    /**
     * Id of the company
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=company")
    public Long company;

    public DeleteContractRequest withCompany(Long company) {
        this.company = company;
        return this;
    }
    
    /**
     * Id of the contract
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=contract")
    public Long contract;

    public DeleteContractRequest withContract(Long contract) {
        this.contract = contract;
        return this;
    }
    
    public DeleteContractRequest(@JsonProperty("company") Long company, @JsonProperty("contract") Long contract) {
        this.company = company;
        this.contract = contract;
  }
}
