/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Contractify.ContractifyAPI.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class DeleteOfficeResponse {
    
    public String contentType;

    public DeleteOfficeResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public DeleteOfficeResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public DeleteOfficeResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * Precondition failed
     */
    
    public DeleteOffice400ApplicationJSON deleteOffice400ApplicationJSONObject;

    public DeleteOfficeResponse withDeleteOffice400ApplicationJSONObject(DeleteOffice400ApplicationJSON deleteOffice400ApplicationJSONObject) {
        this.deleteOffice400ApplicationJSONObject = deleteOffice400ApplicationJSONObject;
        return this;
    }
    
    /**
     * Unauthenticated
     */
    
    public DeleteOffice401ApplicationJSON deleteOffice401ApplicationJSONObject;

    public DeleteOfficeResponse withDeleteOffice401ApplicationJSONObject(DeleteOffice401ApplicationJSON deleteOffice401ApplicationJSONObject) {
        this.deleteOffice401ApplicationJSONObject = deleteOffice401ApplicationJSONObject;
        return this;
    }
    
    /**
     * Forbidden
     */
    
    public DeleteOffice403ApplicationJSON deleteOffice403ApplicationJSONObject;

    public DeleteOfficeResponse withDeleteOffice403ApplicationJSONObject(DeleteOffice403ApplicationJSON deleteOffice403ApplicationJSONObject) {
        this.deleteOffice403ApplicationJSONObject = deleteOffice403ApplicationJSONObject;
        return this;
    }
    
    /**
     * Not Found
     */
    
    public DeleteOffice404ApplicationJSON deleteOffice404ApplicationJSONObject;

    public DeleteOfficeResponse withDeleteOffice404ApplicationJSONObject(DeleteOffice404ApplicationJSON deleteOffice404ApplicationJSONObject) {
        this.deleteOffice404ApplicationJSONObject = deleteOffice404ApplicationJSONObject;
        return this;
    }
    
    public DeleteOfficeResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
