/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Contractify.ContractifyAPI.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class DeleteRelationResponse {
    
    public String contentType;

    public DeleteRelationResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public DeleteRelationResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public DeleteRelationResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * Precondition failed
     */
    
    public DeleteRelation400ApplicationJSON deleteRelation400ApplicationJSONObject;

    public DeleteRelationResponse withDeleteRelation400ApplicationJSONObject(DeleteRelation400ApplicationJSON deleteRelation400ApplicationJSONObject) {
        this.deleteRelation400ApplicationJSONObject = deleteRelation400ApplicationJSONObject;
        return this;
    }
    
    /**
     * Unauthenticated
     */
    
    public DeleteRelation401ApplicationJSON deleteRelation401ApplicationJSONObject;

    public DeleteRelationResponse withDeleteRelation401ApplicationJSONObject(DeleteRelation401ApplicationJSON deleteRelation401ApplicationJSONObject) {
        this.deleteRelation401ApplicationJSONObject = deleteRelation401ApplicationJSONObject;
        return this;
    }
    
    /**
     * Forbidden
     */
    
    public DeleteRelation403ApplicationJSON deleteRelation403ApplicationJSONObject;

    public DeleteRelationResponse withDeleteRelation403ApplicationJSONObject(DeleteRelation403ApplicationJSON deleteRelation403ApplicationJSONObject) {
        this.deleteRelation403ApplicationJSONObject = deleteRelation403ApplicationJSONObject;
        return this;
    }
    
    /**
     * Not Found
     */
    
    public DeleteRelation404ApplicationJSON deleteRelation404ApplicationJSONObject;

    public DeleteRelationResponse withDeleteRelation404ApplicationJSONObject(DeleteRelation404ApplicationJSON deleteRelation404ApplicationJSONObject) {
        this.deleteRelation404ApplicationJSONObject = deleteRelation404ApplicationJSONObject;
        return this;
    }
    
    public DeleteRelationResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
