/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Contractify.ContractifyAPI.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class DeleteDepartmentResponse {
    
    public String contentType;

    public DeleteDepartmentResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public DeleteDepartmentResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public DeleteDepartmentResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * Precondition failed
     */
    
    public DeleteDepartment400ApplicationJSON deleteDepartment400ApplicationJSONObject;

    public DeleteDepartmentResponse withDeleteDepartment400ApplicationJSONObject(DeleteDepartment400ApplicationJSON deleteDepartment400ApplicationJSONObject) {
        this.deleteDepartment400ApplicationJSONObject = deleteDepartment400ApplicationJSONObject;
        return this;
    }
    
    /**
     * Unauthenticated
     */
    
    public DeleteDepartment401ApplicationJSON deleteDepartment401ApplicationJSONObject;

    public DeleteDepartmentResponse withDeleteDepartment401ApplicationJSONObject(DeleteDepartment401ApplicationJSON deleteDepartment401ApplicationJSONObject) {
        this.deleteDepartment401ApplicationJSONObject = deleteDepartment401ApplicationJSONObject;
        return this;
    }
    
    /**
     * Forbidden
     */
    
    public DeleteDepartment403ApplicationJSON deleteDepartment403ApplicationJSONObject;

    public DeleteDepartmentResponse withDeleteDepartment403ApplicationJSONObject(DeleteDepartment403ApplicationJSON deleteDepartment403ApplicationJSONObject) {
        this.deleteDepartment403ApplicationJSONObject = deleteDepartment403ApplicationJSONObject;
        return this;
    }
    
    /**
     * Not Found
     */
    
    public DeleteDepartment404ApplicationJSON deleteDepartment404ApplicationJSONObject;

    public DeleteDepartmentResponse withDeleteDepartment404ApplicationJSONObject(DeleteDepartment404ApplicationJSON deleteDepartment404ApplicationJSONObject) {
        this.deleteDepartment404ApplicationJSONObject = deleteDepartment404ApplicationJSONObject;
        return this;
    }
    
    public DeleteDepartmentResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
