/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Contractify.ContractifyAPI.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class DeleteTaskResponse {
    
    public String contentType;

    public DeleteTaskResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public DeleteTaskResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public DeleteTaskResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * Unauthenticated
     */
    
    public DeleteTask401ApplicationJSON deleteTask401ApplicationJSONObject;

    public DeleteTaskResponse withDeleteTask401ApplicationJSONObject(DeleteTask401ApplicationJSON deleteTask401ApplicationJSONObject) {
        this.deleteTask401ApplicationJSONObject = deleteTask401ApplicationJSONObject;
        return this;
    }
    
    /**
     * Forbidden
     */
    
    public DeleteTask403ApplicationJSON deleteTask403ApplicationJSONObject;

    public DeleteTaskResponse withDeleteTask403ApplicationJSONObject(DeleteTask403ApplicationJSON deleteTask403ApplicationJSONObject) {
        this.deleteTask403ApplicationJSONObject = deleteTask403ApplicationJSONObject;
        return this;
    }
    
    /**
     * Not Found
     */
    
    public DeleteTask404ApplicationJSON deleteTask404ApplicationJSONObject;

    public DeleteTaskResponse withDeleteTask404ApplicationJSONObject(DeleteTask404ApplicationJSON deleteTask404ApplicationJSONObject) {
        this.deleteTask404ApplicationJSONObject = deleteTask404ApplicationJSONObject;
        return this;
    }
    
    public DeleteTaskResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
