/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Contractify.ContractifyAPI.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class DeleteContractResponse {
    
    public String contentType;

    public DeleteContractResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public DeleteContractResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public DeleteContractResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * Precondition failed
     */
    
    public DeleteContract400ApplicationJSON deleteContract400ApplicationJSONObject;

    public DeleteContractResponse withDeleteContract400ApplicationJSONObject(DeleteContract400ApplicationJSON deleteContract400ApplicationJSONObject) {
        this.deleteContract400ApplicationJSONObject = deleteContract400ApplicationJSONObject;
        return this;
    }
    
    /**
     * Unauthenticated
     */
    
    public DeleteContract401ApplicationJSON deleteContract401ApplicationJSONObject;

    public DeleteContractResponse withDeleteContract401ApplicationJSONObject(DeleteContract401ApplicationJSON deleteContract401ApplicationJSONObject) {
        this.deleteContract401ApplicationJSONObject = deleteContract401ApplicationJSONObject;
        return this;
    }
    
    /**
     * Forbidden
     */
    
    public DeleteContract403ApplicationJSON deleteContract403ApplicationJSONObject;

    public DeleteContractResponse withDeleteContract403ApplicationJSONObject(DeleteContract403ApplicationJSON deleteContract403ApplicationJSONObject) {
        this.deleteContract403ApplicationJSONObject = deleteContract403ApplicationJSONObject;
        return this;
    }
    
    /**
     * Not Found
     */
    
    public DeleteContract404ApplicationJSON deleteContract404ApplicationJSONObject;

    public DeleteContractResponse withDeleteContract404ApplicationJSONObject(DeleteContract404ApplicationJSON deleteContract404ApplicationJSONObject) {
        this.deleteContract404ApplicationJSONObject = deleteContract404ApplicationJSONObject;
        return this;
    }
    
    public DeleteContractResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
