/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Contractify.ContractifyAPI.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class GetContractResponse {
    
    public String contentType;

    public GetContractResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public GetContractResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public GetContractResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * OK
     */
    
    public GetContract200ApplicationJSON getContract200ApplicationJSONObject;

    public GetContractResponse withGetContract200ApplicationJSONObject(GetContract200ApplicationJSON getContract200ApplicationJSONObject) {
        this.getContract200ApplicationJSONObject = getContract200ApplicationJSONObject;
        return this;
    }
    
    /**
     * Unauthenticated
     */
    
    public GetContract401ApplicationJSON getContract401ApplicationJSONObject;

    public GetContractResponse withGetContract401ApplicationJSONObject(GetContract401ApplicationJSON getContract401ApplicationJSONObject) {
        this.getContract401ApplicationJSONObject = getContract401ApplicationJSONObject;
        return this;
    }
    
    /**
     * Forbidden
     */
    
    public GetContract403ApplicationJSON getContract403ApplicationJSONObject;

    public GetContractResponse withGetContract403ApplicationJSONObject(GetContract403ApplicationJSON getContract403ApplicationJSONObject) {
        this.getContract403ApplicationJSONObject = getContract403ApplicationJSONObject;
        return this;
    }
    
    /**
     * Not Found
     */
    
    public GetContract404ApplicationJSON getContract404ApplicationJSONObject;

    public GetContractResponse withGetContract404ApplicationJSONObject(GetContract404ApplicationJSON getContract404ApplicationJSONObject) {
        this.getContract404ApplicationJSONObject = getContract404ApplicationJSONObject;
        return this;
    }
    
    public GetContractResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
