/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Contractify.ContractifyAPI.models.operations;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * GetDocument403ApplicationJSON - Forbidden
 */

public class GetDocument403ApplicationJSON {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("message")
    public String message;

    public GetDocument403ApplicationJSON withMessage(String message) {
        this.message = message;
        return this;
    }
    
    public GetDocument403ApplicationJSON(){}
}
