/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Contractify.ContractifyAPI.models.operations;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * GetDocument200ApplicationJSON - OK
 */

public class GetDocument200ApplicationJSON {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("data")
    public Contractify.ContractifyAPI.models.shared.DocumentRead data;

    public GetDocument200ApplicationJSON withData(Contractify.ContractifyAPI.models.shared.DocumentRead data) {
        this.data = data;
        return this;
    }
    
    public GetDocument200ApplicationJSON(){}
}
