/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Contractify.ContractifyAPI.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class GetDepartmentResponse {
    
    public String contentType;

    public GetDepartmentResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public GetDepartmentResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public GetDepartmentResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * OK
     */
    
    public GetDepartment200ApplicationJSON getDepartment200ApplicationJSONObject;

    public GetDepartmentResponse withGetDepartment200ApplicationJSONObject(GetDepartment200ApplicationJSON getDepartment200ApplicationJSONObject) {
        this.getDepartment200ApplicationJSONObject = getDepartment200ApplicationJSONObject;
        return this;
    }
    
    /**
     * Unauthenticated
     */
    
    public GetDepartment401ApplicationJSON getDepartment401ApplicationJSONObject;

    public GetDepartmentResponse withGetDepartment401ApplicationJSONObject(GetDepartment401ApplicationJSON getDepartment401ApplicationJSONObject) {
        this.getDepartment401ApplicationJSONObject = getDepartment401ApplicationJSONObject;
        return this;
    }
    
    /**
     * Forbidden
     */
    
    public GetDepartment403ApplicationJSON getDepartment403ApplicationJSONObject;

    public GetDepartmentResponse withGetDepartment403ApplicationJSONObject(GetDepartment403ApplicationJSON getDepartment403ApplicationJSONObject) {
        this.getDepartment403ApplicationJSONObject = getDepartment403ApplicationJSONObject;
        return this;
    }
    
    /**
     * Not Found
     */
    
    public GetDepartment404ApplicationJSON getDepartment404ApplicationJSONObject;

    public GetDepartmentResponse withGetDepartment404ApplicationJSONObject(GetDepartment404ApplicationJSON getDepartment404ApplicationJSONObject) {
        this.getDepartment404ApplicationJSONObject = getDepartment404ApplicationJSONObject;
        return this;
    }
    
    public GetDepartmentResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
