/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Contractify.ContractifyAPI.models.operations;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * GetDepartment200ApplicationJSON - OK
 */

public class GetDepartment200ApplicationJSON {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("data")
    public Contractify.ContractifyAPI.models.shared.DepartmentRead data;

    public GetDepartment200ApplicationJSON withData(Contractify.ContractifyAPI.models.shared.DepartmentRead data) {
        this.data = data;
        return this;
    }
    
    public GetDepartment200ApplicationJSON(){}
}
