/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Contractify.ContractifyAPI.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class GetDocumentResponse {
    
    public String contentType;

    public GetDocumentResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public GetDocumentResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public GetDocumentResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * OK
     */
    
    public GetDocument200ApplicationJSON getDocument200ApplicationJSONObject;

    public GetDocumentResponse withGetDocument200ApplicationJSONObject(GetDocument200ApplicationJSON getDocument200ApplicationJSONObject) {
        this.getDocument200ApplicationJSONObject = getDocument200ApplicationJSONObject;
        return this;
    }
    
    /**
     * Unauthenticated
     */
    
    public GetDocument401ApplicationJSON getDocument401ApplicationJSONObject;

    public GetDocumentResponse withGetDocument401ApplicationJSONObject(GetDocument401ApplicationJSON getDocument401ApplicationJSONObject) {
        this.getDocument401ApplicationJSONObject = getDocument401ApplicationJSONObject;
        return this;
    }
    
    /**
     * Forbidden
     */
    
    public GetDocument403ApplicationJSON getDocument403ApplicationJSONObject;

    public GetDocumentResponse withGetDocument403ApplicationJSONObject(GetDocument403ApplicationJSON getDocument403ApplicationJSONObject) {
        this.getDocument403ApplicationJSONObject = getDocument403ApplicationJSONObject;
        return this;
    }
    
    /**
     * Not Found
     */
    
    public GetDocument404ApplicationJSON getDocument404ApplicationJSONObject;

    public GetDocumentResponse withGetDocument404ApplicationJSONObject(GetDocument404ApplicationJSON getDocument404ApplicationJSONObject) {
        this.getDocument404ApplicationJSONObject = getDocument404ApplicationJSONObject;
        return this;
    }
    
    public GetDocumentResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
