/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Contractify.ContractifyAPI.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class GetOfficeResponse {
    
    public String contentType;

    public GetOfficeResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public GetOfficeResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public GetOfficeResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * OK
     */
    
    public GetOffice200ApplicationJSON getOffice200ApplicationJSONObject;

    public GetOfficeResponse withGetOffice200ApplicationJSONObject(GetOffice200ApplicationJSON getOffice200ApplicationJSONObject) {
        this.getOffice200ApplicationJSONObject = getOffice200ApplicationJSONObject;
        return this;
    }
    
    /**
     * Unauthenticated
     */
    
    public GetOffice401ApplicationJSON getOffice401ApplicationJSONObject;

    public GetOfficeResponse withGetOffice401ApplicationJSONObject(GetOffice401ApplicationJSON getOffice401ApplicationJSONObject) {
        this.getOffice401ApplicationJSONObject = getOffice401ApplicationJSONObject;
        return this;
    }
    
    /**
     * Forbidden
     */
    
    public GetOffice403ApplicationJSON getOffice403ApplicationJSONObject;

    public GetOfficeResponse withGetOffice403ApplicationJSONObject(GetOffice403ApplicationJSON getOffice403ApplicationJSONObject) {
        this.getOffice403ApplicationJSONObject = getOffice403ApplicationJSONObject;
        return this;
    }
    
    /**
     * Not Found
     */
    
    public GetOffice404ApplicationJSON getOffice404ApplicationJSONObject;

    public GetOfficeResponse withGetOffice404ApplicationJSONObject(GetOffice404ApplicationJSON getOffice404ApplicationJSONObject) {
        this.getOffice404ApplicationJSONObject = getOffice404ApplicationJSONObject;
        return this;
    }
    
    public GetOfficeResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
