/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Contractify.ContractifyAPI.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class GetRelationResponse {
    
    public String contentType;

    public GetRelationResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public GetRelationResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public GetRelationResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * OK
     */
    
    public GetRelation200ApplicationJSON getRelation200ApplicationJSONObject;

    public GetRelationResponse withGetRelation200ApplicationJSONObject(GetRelation200ApplicationJSON getRelation200ApplicationJSONObject) {
        this.getRelation200ApplicationJSONObject = getRelation200ApplicationJSONObject;
        return this;
    }
    
    /**
     * Unauthenticated
     */
    
    public GetRelation401ApplicationJSON getRelation401ApplicationJSONObject;

    public GetRelationResponse withGetRelation401ApplicationJSONObject(GetRelation401ApplicationJSON getRelation401ApplicationJSONObject) {
        this.getRelation401ApplicationJSONObject = getRelation401ApplicationJSONObject;
        return this;
    }
    
    /**
     * Forbidden
     */
    
    public GetRelation403ApplicationJSON getRelation403ApplicationJSONObject;

    public GetRelationResponse withGetRelation403ApplicationJSONObject(GetRelation403ApplicationJSON getRelation403ApplicationJSONObject) {
        this.getRelation403ApplicationJSONObject = getRelation403ApplicationJSONObject;
        return this;
    }
    
    /**
     * Not Found
     */
    
    public GetRelation404ApplicationJSON getRelation404ApplicationJSONObject;

    public GetRelationResponse withGetRelation404ApplicationJSONObject(GetRelation404ApplicationJSON getRelation404ApplicationJSONObject) {
        this.getRelation404ApplicationJSONObject = getRelation404ApplicationJSONObject;
        return this;
    }
    
    public GetRelationResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
