/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Contractify.ContractifyAPI.models.operations;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * GetTask200ApplicationJSON - OK
 */

public class GetTask200ApplicationJSON {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("data")
    public Contractify.ContractifyAPI.models.shared.TaskRead data;

    public GetTask200ApplicationJSON withData(Contractify.ContractifyAPI.models.shared.TaskRead data) {
        this.data = data;
        return this;
    }
    
    public GetTask200ApplicationJSON(){}
}
