/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Contractify.ContractifyAPI.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class GetTaskResponse {
    
    public String contentType;

    public GetTaskResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public GetTaskResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public GetTaskResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * OK
     */
    
    public GetTask200ApplicationJSON getTask200ApplicationJSONObject;

    public GetTaskResponse withGetTask200ApplicationJSONObject(GetTask200ApplicationJSON getTask200ApplicationJSONObject) {
        this.getTask200ApplicationJSONObject = getTask200ApplicationJSONObject;
        return this;
    }
    
    /**
     * Unauthenticated
     */
    
    public GetTask401ApplicationJSON getTask401ApplicationJSONObject;

    public GetTaskResponse withGetTask401ApplicationJSONObject(GetTask401ApplicationJSON getTask401ApplicationJSONObject) {
        this.getTask401ApplicationJSONObject = getTask401ApplicationJSONObject;
        return this;
    }
    
    /**
     * Forbidden
     */
    
    public GetTask403ApplicationJSON getTask403ApplicationJSONObject;

    public GetTaskResponse withGetTask403ApplicationJSONObject(GetTask403ApplicationJSON getTask403ApplicationJSONObject) {
        this.getTask403ApplicationJSONObject = getTask403ApplicationJSONObject;
        return this;
    }
    
    /**
     * Not Found
     */
    
    public GetTask404ApplicationJSON getTask404ApplicationJSONObject;

    public GetTaskResponse withGetTask404ApplicationJSONObject(GetTask404ApplicationJSON getTask404ApplicationJSONObject) {
        this.getTask404ApplicationJSONObject = getTask404ApplicationJSONObject;
        return this;
    }
    
    public GetTaskResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
