/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Contractify.ContractifyAPI.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class ListTasksResponse {
    
    public String contentType;

    public ListTasksResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public ListTasksResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public ListTasksResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * OK
     */
    
    public Contractify.ContractifyAPI.models.shared.TaskCollection taskCollection;

    public ListTasksResponse withTaskCollection(Contractify.ContractifyAPI.models.shared.TaskCollection taskCollection) {
        this.taskCollection = taskCollection;
        return this;
    }
    
    /**
     * Unauthenticated
     */
    
    public ListTasks401ApplicationJSON listTasks401ApplicationJSONObject;

    public ListTasksResponse withListTasks401ApplicationJSONObject(ListTasks401ApplicationJSON listTasks401ApplicationJSONObject) {
        this.listTasks401ApplicationJSONObject = listTasks401ApplicationJSONObject;
        return this;
    }
    
    /**
     * Forbidden
     */
    
    public ListTasks403ApplicationJSON listTasks403ApplicationJSONObject;

    public ListTasksResponse withListTasks403ApplicationJSONObject(ListTasks403ApplicationJSON listTasks403ApplicationJSONObject) {
        this.listTasks403ApplicationJSONObject = listTasks403ApplicationJSONObject;
        return this;
    }
    
    public ListTasksResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
