/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Contractify.ContractifyAPI.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class ListContractTypesResponse {
    
    public String contentType;

    public ListContractTypesResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * OK
     */
    
    public Contractify.ContractifyAPI.models.shared.ContractTypeCollection contractTypeCollection;

    public ListContractTypesResponse withContractTypeCollection(Contractify.ContractifyAPI.models.shared.ContractTypeCollection contractTypeCollection) {
        this.contractTypeCollection = contractTypeCollection;
        return this;
    }
    
    
    public Integer statusCode;

    public ListContractTypesResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public ListContractTypesResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * Unauthenticated
     */
    
    public ListContractTypes401ApplicationJSON listContractTypes401ApplicationJSONObject;

    public ListContractTypesResponse withListContractTypes401ApplicationJSONObject(ListContractTypes401ApplicationJSON listContractTypes401ApplicationJSONObject) {
        this.listContractTypes401ApplicationJSONObject = listContractTypes401ApplicationJSONObject;
        return this;
    }
    
    /**
     * Forbidden
     */
    
    public ListContractTypes403ApplicationJSON listContractTypes403ApplicationJSONObject;

    public ListContractTypesResponse withListContractTypes403ApplicationJSONObject(ListContractTypes403ApplicationJSON listContractTypes403ApplicationJSONObject) {
        this.listContractTypes403ApplicationJSONObject = listContractTypes403ApplicationJSONObject;
        return this;
    }
    
    public ListContractTypesResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
