/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Contractify.ContractifyAPI.models.operations;

import Contractify.ContractifyAPI.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;


public class ListRelationsRequest {
    /**
     * Id of the company
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=company")
    public Long company;

    public ListRelationsRequest withCompany(Long company) {
        this.company = company;
        return this;
    }
    
    /**
     * The page to retrieve
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=page")
    public Long page;

    public ListRelationsRequest withPage(Long page) {
        this.page = page;
        return this;
    }
    
    /**
     * Return relations with a certain reference
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=reference")
    public String reference;

    public ListRelationsRequest withReference(String reference) {
        this.reference = reference;
        return this;
    }
    
    public ListRelationsRequest(@JsonProperty("company") Long company) {
        this.company = company;
  }
}
