/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Contractify.ContractifyAPI.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class ListSubfoldersResponse {
    
    public String contentType;

    public ListSubfoldersResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * OK
     */
    
    public Contractify.ContractifyAPI.models.shared.DossierCollection dossierCollection;

    public ListSubfoldersResponse withDossierCollection(Contractify.ContractifyAPI.models.shared.DossierCollection dossierCollection) {
        this.dossierCollection = dossierCollection;
        return this;
    }
    
    
    public Integer statusCode;

    public ListSubfoldersResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public ListSubfoldersResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * Unauthenticated
     */
    
    public ListSubfolders401ApplicationJSON listSubfolders401ApplicationJSONObject;

    public ListSubfoldersResponse withListSubfolders401ApplicationJSONObject(ListSubfolders401ApplicationJSON listSubfolders401ApplicationJSONObject) {
        this.listSubfolders401ApplicationJSONObject = listSubfolders401ApplicationJSONObject;
        return this;
    }
    
    /**
     * Forbidden
     */
    
    public ListSubfolders403ApplicationJSON listSubfolders403ApplicationJSONObject;

    public ListSubfoldersResponse withListSubfolders403ApplicationJSONObject(ListSubfolders403ApplicationJSON listSubfolders403ApplicationJSONObject) {
        this.listSubfolders403ApplicationJSONObject = listSubfolders403ApplicationJSONObject;
        return this;
    }
    
    public ListSubfoldersResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
