/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Contractify.ContractifyAPI.models.operations;

import Contractify.ContractifyAPI.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;


public class ListLegalEntitiesRequest {
    /**
     * Id of the company
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=company")
    public Long company;

    public ListLegalEntitiesRequest withCompany(Long company) {
        this.company = company;
        return this;
    }
    
    public ListLegalEntitiesRequest(@JsonProperty("company") Long company) {
        this.company = company;
  }
}
