/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Contractify.ContractifyAPI.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class ListLegalEntitiesResponse {
    
    public String contentType;

    public ListLegalEntitiesResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * OK
     */
    
    public Contractify.ContractifyAPI.models.shared.LegalEntityCollection legalEntityCollection;

    public ListLegalEntitiesResponse withLegalEntityCollection(Contractify.ContractifyAPI.models.shared.LegalEntityCollection legalEntityCollection) {
        this.legalEntityCollection = legalEntityCollection;
        return this;
    }
    
    
    public Integer statusCode;

    public ListLegalEntitiesResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public ListLegalEntitiesResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * Unauthenticated
     */
    
    public ListLegalEntities401ApplicationJSON listLegalEntities401ApplicationJSONObject;

    public ListLegalEntitiesResponse withListLegalEntities401ApplicationJSONObject(ListLegalEntities401ApplicationJSON listLegalEntities401ApplicationJSONObject) {
        this.listLegalEntities401ApplicationJSONObject = listLegalEntities401ApplicationJSONObject;
        return this;
    }
    
    /**
     * Forbidden
     */
    
    public ListLegalEntities403ApplicationJSON listLegalEntities403ApplicationJSONObject;

    public ListLegalEntitiesResponse withListLegalEntities403ApplicationJSONObject(ListLegalEntities403ApplicationJSON listLegalEntities403ApplicationJSONObject) {
        this.listLegalEntities403ApplicationJSONObject = listLegalEntities403ApplicationJSONObject;
        return this;
    }
    
    public ListLegalEntitiesResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
