/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Contractify.ContractifyAPI.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class ListDocumentsResponse {
    
    public String contentType;

    public ListDocumentsResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * OK
     */
    
    public Contractify.ContractifyAPI.models.shared.DocumentCollection documentCollection;

    public ListDocumentsResponse withDocumentCollection(Contractify.ContractifyAPI.models.shared.DocumentCollection documentCollection) {
        this.documentCollection = documentCollection;
        return this;
    }
    
    
    public Integer statusCode;

    public ListDocumentsResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public ListDocumentsResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * Unauthenticated
     */
    
    public ListDocuments401ApplicationJSON listDocuments401ApplicationJSONObject;

    public ListDocumentsResponse withListDocuments401ApplicationJSONObject(ListDocuments401ApplicationJSON listDocuments401ApplicationJSONObject) {
        this.listDocuments401ApplicationJSONObject = listDocuments401ApplicationJSONObject;
        return this;
    }
    
    /**
     * Forbidden
     */
    
    public ListDocuments403ApplicationJSON listDocuments403ApplicationJSONObject;

    public ListDocumentsResponse withListDocuments403ApplicationJSONObject(ListDocuments403ApplicationJSON listDocuments403ApplicationJSONObject) {
        this.listDocuments403ApplicationJSONObject = listDocuments403ApplicationJSONObject;
        return this;
    }
    
    public ListDocumentsResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
