/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Contractify.ContractifyAPI.models.operations;

import Contractify.ContractifyAPI.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;


public class ListTasksRequest {
    /**
     * Id of the company
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=company")
    public Long company;

    public ListTasksRequest withCompany(Long company) {
        this.company = company;
        return this;
    }
    
    /**
     * The page to retrieve
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=page")
    public Long page;

    public ListTasksRequest withPage(Long page) {
        this.page = page;
        return this;
    }
    
    public ListTasksRequest(@JsonProperty("company") Long company) {
        this.company = company;
  }
}
