/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Contractify.ContractifyAPI.models.operations;

import Contractify.ContractifyAPI.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.time.OffsetDateTime;


public class ListDocumentsRequest {
    /**
     * Id of the company
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=company")
    public Long company;

    public ListDocumentsRequest withCompany(Long company) {
        this.company = company;
        return this;
    }
    
    /**
     * Return documents currently having this status in the eSigning process, can be comma separated
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=esigning_status")
    public ListDocumentsEsigningStatus esigningStatus;

    public ListDocumentsRequest withEsigningStatus(ListDocumentsEsigningStatus esigningStatus) {
        this.esigningStatus = esigningStatus;
        return this;
    }
    
    /**
     * Return documents where e-signing was updated after the given date
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=esigning_updated_after")
    public OffsetDateTime esigningUpdatedAfter;

    public ListDocumentsRequest withEsigningUpdatedAfter(OffsetDateTime esigningUpdatedAfter) {
        this.esigningUpdatedAfter = esigningUpdatedAfter;
        return this;
    }
    
    /**
     * The page to retrieve
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=page")
    public Long page;

    public ListDocumentsRequest withPage(Long page) {
        this.page = page;
        return this;
    }
    
    /**
     * Return documents linked to a relation
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=relation_id")
    public Long relationId;

    public ListDocumentsRequest withRelationId(Long relationId) {
        this.relationId = relationId;
        return this;
    }
    
    /**
     * Return documents e-signed after the given date
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=signed_after")
    public OffsetDateTime signedAfter;

    public ListDocumentsRequest withSignedAfter(OffsetDateTime signedAfter) {
        this.signedAfter = signedAfter;
        return this;
    }
    
    public ListDocumentsRequest(@JsonProperty("company") Long company) {
        this.company = company;
  }
}
