/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Contractify.ContractifyAPI.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class ListRelationsResponse {
    
    public String contentType;

    public ListRelationsResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * OK
     */
    
    public Contractify.ContractifyAPI.models.shared.RelationCollection relationCollection;

    public ListRelationsResponse withRelationCollection(Contractify.ContractifyAPI.models.shared.RelationCollection relationCollection) {
        this.relationCollection = relationCollection;
        return this;
    }
    
    
    public Integer statusCode;

    public ListRelationsResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public ListRelationsResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * Unauthenticated
     */
    
    public ListRelations401ApplicationJSON listRelations401ApplicationJSONObject;

    public ListRelationsResponse withListRelations401ApplicationJSONObject(ListRelations401ApplicationJSON listRelations401ApplicationJSONObject) {
        this.listRelations401ApplicationJSONObject = listRelations401ApplicationJSONObject;
        return this;
    }
    
    /**
     * Forbidden
     */
    
    public ListRelations403ApplicationJSON listRelations403ApplicationJSONObject;

    public ListRelationsResponse withListRelations403ApplicationJSONObject(ListRelations403ApplicationJSON listRelations403ApplicationJSONObject) {
        this.listRelations403ApplicationJSONObject = listRelations403ApplicationJSONObject;
        return this;
    }
    
    public ListRelationsResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
