/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Contractify.ContractifyAPI.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class ListCustomFieldsResponse {
    
    public String contentType;

    public ListCustomFieldsResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * OK
     */
    
    public Contractify.ContractifyAPI.models.shared.CustomFieldCollection customFieldCollection;

    public ListCustomFieldsResponse withCustomFieldCollection(Contractify.ContractifyAPI.models.shared.CustomFieldCollection customFieldCollection) {
        this.customFieldCollection = customFieldCollection;
        return this;
    }
    
    
    public Integer statusCode;

    public ListCustomFieldsResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public ListCustomFieldsResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * Unauthenticated
     */
    
    public ListCustomFields401ApplicationJSON listCustomFields401ApplicationJSONObject;

    public ListCustomFieldsResponse withListCustomFields401ApplicationJSONObject(ListCustomFields401ApplicationJSON listCustomFields401ApplicationJSONObject) {
        this.listCustomFields401ApplicationJSONObject = listCustomFields401ApplicationJSONObject;
        return this;
    }
    
    /**
     * Forbidden
     */
    
    public ListCustomFields403ApplicationJSON listCustomFields403ApplicationJSONObject;

    public ListCustomFieldsResponse withListCustomFields403ApplicationJSONObject(ListCustomFields403ApplicationJSON listCustomFields403ApplicationJSONObject) {
        this.listCustomFields403ApplicationJSONObject = listCustomFields403ApplicationJSONObject;
        return this;
    }
    
    public ListCustomFieldsResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
