/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Contractify.ContractifyAPI.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * ListDocumentsEsigningStatus - Return documents currently having this status in the eSigning process, can be comma separated
 */
public enum ListDocumentsEsigningStatus {
    NOT_SENT("not_sent"),
    SENT_TO_LEGAL("sent_to_legal"),
    LEGAL_DECLINED("legal_declined"),
    SENT("sent"),
    SIGNED("signed"),
    REJECTED_BY_SIGNER("rejected_by_signer"),
    FINISHED_BUT_PARTIALLY_SIGNED("finished_but_partially_signed"),
    REVOKED("revoked");

    @JsonValue
    public final String value;

    private ListDocumentsEsigningStatus(String value) {
        this.value = value;
    }
}
