/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Contractify.ContractifyAPI.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class ListOfficesResponse {
    
    public String contentType;

    public ListOfficesResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * OK
     */
    
    public Contractify.ContractifyAPI.models.shared.OfficeCollection officeCollection;

    public ListOfficesResponse withOfficeCollection(Contractify.ContractifyAPI.models.shared.OfficeCollection officeCollection) {
        this.officeCollection = officeCollection;
        return this;
    }
    
    
    public Integer statusCode;

    public ListOfficesResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public ListOfficesResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * Unauthenticated
     */
    
    public ListOffices401ApplicationJSON listOffices401ApplicationJSONObject;

    public ListOfficesResponse withListOffices401ApplicationJSONObject(ListOffices401ApplicationJSON listOffices401ApplicationJSONObject) {
        this.listOffices401ApplicationJSONObject = listOffices401ApplicationJSONObject;
        return this;
    }
    
    /**
     * Forbidden
     */
    
    public ListOffices403ApplicationJSON listOffices403ApplicationJSONObject;

    public ListOfficesResponse withListOffices403ApplicationJSONObject(ListOffices403ApplicationJSON listOffices403ApplicationJSONObject) {
        this.listOffices403ApplicationJSONObject = listOffices403ApplicationJSONObject;
        return this;
    }
    
    public ListOfficesResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
