/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Contractify.ContractifyAPI.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class ListUsersResponse {
    
    public String contentType;

    public ListUsersResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public ListUsersResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public ListUsersResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * OK
     */
    
    public Contractify.ContractifyAPI.models.shared.UserCollection userCollection;

    public ListUsersResponse withUserCollection(Contractify.ContractifyAPI.models.shared.UserCollection userCollection) {
        this.userCollection = userCollection;
        return this;
    }
    
    /**
     * Unauthenticated
     */
    
    public ListUsers401ApplicationJSON listUsers401ApplicationJSONObject;

    public ListUsersResponse withListUsers401ApplicationJSONObject(ListUsers401ApplicationJSON listUsers401ApplicationJSONObject) {
        this.listUsers401ApplicationJSONObject = listUsers401ApplicationJSONObject;
        return this;
    }
    
    /**
     * Forbidden
     */
    
    public ListUsers403ApplicationJSON listUsers403ApplicationJSONObject;

    public ListUsersResponse withListUsers403ApplicationJSONObject(ListUsers403ApplicationJSON listUsers403ApplicationJSONObject) {
        this.listUsers403ApplicationJSONObject = listUsers403ApplicationJSONObject;
        return this;
    }
    
    public ListUsersResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
