/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Contractify.ContractifyAPI.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class ListDepartmentsResponse {
    
    public String contentType;

    public ListDepartmentsResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * OK
     */
    
    public Contractify.ContractifyAPI.models.shared.DepartmentCollection departmentCollection;

    public ListDepartmentsResponse withDepartmentCollection(Contractify.ContractifyAPI.models.shared.DepartmentCollection departmentCollection) {
        this.departmentCollection = departmentCollection;
        return this;
    }
    
    
    public Integer statusCode;

    public ListDepartmentsResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public ListDepartmentsResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * Unauthenticated
     */
    
    public ListDepartments401ApplicationJSON listDepartments401ApplicationJSONObject;

    public ListDepartmentsResponse withListDepartments401ApplicationJSONObject(ListDepartments401ApplicationJSON listDepartments401ApplicationJSONObject) {
        this.listDepartments401ApplicationJSONObject = listDepartments401ApplicationJSONObject;
        return this;
    }
    
    /**
     * Forbidden
     */
    
    public ListDepartments403ApplicationJSON listDepartments403ApplicationJSONObject;

    public ListDepartmentsResponse withListDepartments403ApplicationJSONObject(ListDepartments403ApplicationJSON listDepartments403ApplicationJSONObject) {
        this.listDepartments403ApplicationJSONObject = listDepartments403ApplicationJSONObject;
        return this;
    }
    
    public ListDepartmentsResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
