/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Contractify.ContractifyAPI.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class ListContractsResponse {
    
    public String contentType;

    public ListContractsResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * OK
     */
    
    public Contractify.ContractifyAPI.models.shared.ContractCollection contractCollection;

    public ListContractsResponse withContractCollection(Contractify.ContractifyAPI.models.shared.ContractCollection contractCollection) {
        this.contractCollection = contractCollection;
        return this;
    }
    
    
    public Integer statusCode;

    public ListContractsResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public ListContractsResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * Unauthenticated
     */
    
    public ListContracts401ApplicationJSON listContracts401ApplicationJSONObject;

    public ListContractsResponse withListContracts401ApplicationJSONObject(ListContracts401ApplicationJSON listContracts401ApplicationJSONObject) {
        this.listContracts401ApplicationJSONObject = listContracts401ApplicationJSONObject;
        return this;
    }
    
    /**
     * Forbidden
     */
    
    public ListContracts403ApplicationJSON listContracts403ApplicationJSONObject;

    public ListContractsResponse withListContracts403ApplicationJSONObject(ListContracts403ApplicationJSON listContracts403ApplicationJSONObject) {
        this.listContracts403ApplicationJSONObject = listContracts403ApplicationJSONObject;
        return this;
    }
    
    public ListContractsResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
