/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Contractify.ContractifyAPI.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class UpdateTaskResponse {
    
    public String contentType;

    public UpdateTaskResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public UpdateTaskResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public UpdateTaskResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * OK
     */
    
    public UpdateTask200ApplicationJSON updateTask200ApplicationJSONObject;

    public UpdateTaskResponse withUpdateTask200ApplicationJSONObject(UpdateTask200ApplicationJSON updateTask200ApplicationJSONObject) {
        this.updateTask200ApplicationJSONObject = updateTask200ApplicationJSONObject;
        return this;
    }
    
    /**
     * Unauthenticated
     */
    
    public UpdateTask401ApplicationJSON updateTask401ApplicationJSONObject;

    public UpdateTaskResponse withUpdateTask401ApplicationJSONObject(UpdateTask401ApplicationJSON updateTask401ApplicationJSONObject) {
        this.updateTask401ApplicationJSONObject = updateTask401ApplicationJSONObject;
        return this;
    }
    
    /**
     * Forbidden
     */
    
    public UpdateTask403ApplicationJSON updateTask403ApplicationJSONObject;

    public UpdateTaskResponse withUpdateTask403ApplicationJSONObject(UpdateTask403ApplicationJSON updateTask403ApplicationJSONObject) {
        this.updateTask403ApplicationJSONObject = updateTask403ApplicationJSONObject;
        return this;
    }
    
    /**
     * Not Found
     */
    
    public UpdateTask404ApplicationJSON updateTask404ApplicationJSONObject;

    public UpdateTaskResponse withUpdateTask404ApplicationJSONObject(UpdateTask404ApplicationJSON updateTask404ApplicationJSONObject) {
        this.updateTask404ApplicationJSONObject = updateTask404ApplicationJSONObject;
        return this;
    }
    
    /**
     * Invalid data posted
     */
    
    public UpdateTask422ApplicationJSON updateTask422ApplicationJSONObject;

    public UpdateTaskResponse withUpdateTask422ApplicationJSONObject(UpdateTask422ApplicationJSON updateTask422ApplicationJSONObject) {
        this.updateTask422ApplicationJSONObject = updateTask422ApplicationJSONObject;
        return this;
    }
    
    public UpdateTaskResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
