/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Contractify.ContractifyAPI.models.operations;

import Contractify.ContractifyAPI.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;


public class UpdateContractRequest {
    @SpeakeasyMetadata("request:mediaType=application/json")
    public Contractify.ContractifyAPI.models.shared.ContractWrite contractWrite;

    public UpdateContractRequest withContractWrite(Contractify.ContractifyAPI.models.shared.ContractWrite contractWrite) {
        this.contractWrite = contractWrite;
        return this;
    }
    
    /**
     * Id of the company
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=company")
    public Long company;

    public UpdateContractRequest withCompany(Long company) {
        this.company = company;
        return this;
    }
    
    /**
     * Id of the contract
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=contract")
    public Long contract;

    public UpdateContractRequest withContract(Long contract) {
        this.contract = contract;
        return this;
    }
    
    public UpdateContractRequest(@JsonProperty("company") Long company, @JsonProperty("contract") Long contract) {
        this.company = company;
        this.contract = contract;
  }
}
