/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Contractify.ContractifyAPI.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class UpdateDepartmentResponse {
    
    public String contentType;

    public UpdateDepartmentResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public UpdateDepartmentResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public UpdateDepartmentResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * OK
     */
    
    public UpdateDepartment200ApplicationJSON updateDepartment200ApplicationJSONObject;

    public UpdateDepartmentResponse withUpdateDepartment200ApplicationJSONObject(UpdateDepartment200ApplicationJSON updateDepartment200ApplicationJSONObject) {
        this.updateDepartment200ApplicationJSONObject = updateDepartment200ApplicationJSONObject;
        return this;
    }
    
    /**
     * Unauthenticated
     */
    
    public UpdateDepartment401ApplicationJSON updateDepartment401ApplicationJSONObject;

    public UpdateDepartmentResponse withUpdateDepartment401ApplicationJSONObject(UpdateDepartment401ApplicationJSON updateDepartment401ApplicationJSONObject) {
        this.updateDepartment401ApplicationJSONObject = updateDepartment401ApplicationJSONObject;
        return this;
    }
    
    /**
     * Forbidden
     */
    
    public UpdateDepartment403ApplicationJSON updateDepartment403ApplicationJSONObject;

    public UpdateDepartmentResponse withUpdateDepartment403ApplicationJSONObject(UpdateDepartment403ApplicationJSON updateDepartment403ApplicationJSONObject) {
        this.updateDepartment403ApplicationJSONObject = updateDepartment403ApplicationJSONObject;
        return this;
    }
    
    /**
     * Not Found
     */
    
    public UpdateDepartment404ApplicationJSON updateDepartment404ApplicationJSONObject;

    public UpdateDepartmentResponse withUpdateDepartment404ApplicationJSONObject(UpdateDepartment404ApplicationJSON updateDepartment404ApplicationJSONObject) {
        this.updateDepartment404ApplicationJSONObject = updateDepartment404ApplicationJSONObject;
        return this;
    }
    
    /**
     * Invalid data posted
     */
    
    public UpdateDepartment422ApplicationJSON updateDepartment422ApplicationJSONObject;

    public UpdateDepartmentResponse withUpdateDepartment422ApplicationJSONObject(UpdateDepartment422ApplicationJSON updateDepartment422ApplicationJSONObject) {
        this.updateDepartment422ApplicationJSONObject = updateDepartment422ApplicationJSONObject;
        return this;
    }
    
    public UpdateDepartmentResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
