/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Contractify.ContractifyAPI.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class UpdateRelationResponse {
    
    public String contentType;

    public UpdateRelationResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public UpdateRelationResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public UpdateRelationResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * OK
     */
    
    public UpdateRelation200ApplicationJSON updateRelation200ApplicationJSONObject;

    public UpdateRelationResponse withUpdateRelation200ApplicationJSONObject(UpdateRelation200ApplicationJSON updateRelation200ApplicationJSONObject) {
        this.updateRelation200ApplicationJSONObject = updateRelation200ApplicationJSONObject;
        return this;
    }
    
    /**
     * Unauthenticated
     */
    
    public UpdateRelation401ApplicationJSON updateRelation401ApplicationJSONObject;

    public UpdateRelationResponse withUpdateRelation401ApplicationJSONObject(UpdateRelation401ApplicationJSON updateRelation401ApplicationJSONObject) {
        this.updateRelation401ApplicationJSONObject = updateRelation401ApplicationJSONObject;
        return this;
    }
    
    /**
     * Forbidden
     */
    
    public UpdateRelation403ApplicationJSON updateRelation403ApplicationJSONObject;

    public UpdateRelationResponse withUpdateRelation403ApplicationJSONObject(UpdateRelation403ApplicationJSON updateRelation403ApplicationJSONObject) {
        this.updateRelation403ApplicationJSONObject = updateRelation403ApplicationJSONObject;
        return this;
    }
    
    /**
     * Not Found
     */
    
    public UpdateRelation404ApplicationJSON updateRelation404ApplicationJSONObject;

    public UpdateRelationResponse withUpdateRelation404ApplicationJSONObject(UpdateRelation404ApplicationJSON updateRelation404ApplicationJSONObject) {
        this.updateRelation404ApplicationJSONObject = updateRelation404ApplicationJSONObject;
        return this;
    }
    
    /**
     * Invalid data posted
     */
    
    public UpdateRelation422ApplicationJSON updateRelation422ApplicationJSONObject;

    public UpdateRelationResponse withUpdateRelation422ApplicationJSONObject(UpdateRelation422ApplicationJSON updateRelation422ApplicationJSONObject) {
        this.updateRelation422ApplicationJSONObject = updateRelation422ApplicationJSONObject;
        return this;
    }
    
    public UpdateRelationResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
