/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Contractify.ContractifyAPI.models.operations;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * UpdateOffice200ApplicationJSON - OK
 */

public class UpdateOffice200ApplicationJSON {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("data")
    public Contractify.ContractifyAPI.models.shared.OfficeRead data;

    public UpdateOffice200ApplicationJSON withData(Contractify.ContractifyAPI.models.shared.OfficeRead data) {
        this.data = data;
        return this;
    }
    
    public UpdateOffice200ApplicationJSON(){}
}
