/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Contractify.ContractifyAPI.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class UpdateOfficeResponse {
    
    public String contentType;

    public UpdateOfficeResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public UpdateOfficeResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public UpdateOfficeResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * OK
     */
    
    public UpdateOffice200ApplicationJSON updateOffice200ApplicationJSONObject;

    public UpdateOfficeResponse withUpdateOffice200ApplicationJSONObject(UpdateOffice200ApplicationJSON updateOffice200ApplicationJSONObject) {
        this.updateOffice200ApplicationJSONObject = updateOffice200ApplicationJSONObject;
        return this;
    }
    
    /**
     * Unauthenticated
     */
    
    public UpdateOffice401ApplicationJSON updateOffice401ApplicationJSONObject;

    public UpdateOfficeResponse withUpdateOffice401ApplicationJSONObject(UpdateOffice401ApplicationJSON updateOffice401ApplicationJSONObject) {
        this.updateOffice401ApplicationJSONObject = updateOffice401ApplicationJSONObject;
        return this;
    }
    
    /**
     * Forbidden
     */
    
    public UpdateOffice403ApplicationJSON updateOffice403ApplicationJSONObject;

    public UpdateOfficeResponse withUpdateOffice403ApplicationJSONObject(UpdateOffice403ApplicationJSON updateOffice403ApplicationJSONObject) {
        this.updateOffice403ApplicationJSONObject = updateOffice403ApplicationJSONObject;
        return this;
    }
    
    /**
     * Not Found
     */
    
    public UpdateOffice404ApplicationJSON updateOffice404ApplicationJSONObject;

    public UpdateOfficeResponse withUpdateOffice404ApplicationJSONObject(UpdateOffice404ApplicationJSON updateOffice404ApplicationJSONObject) {
        this.updateOffice404ApplicationJSONObject = updateOffice404ApplicationJSONObject;
        return this;
    }
    
    /**
     * Invalid data posted
     */
    
    public UpdateOffice422ApplicationJSON updateOffice422ApplicationJSONObject;

    public UpdateOfficeResponse withUpdateOffice422ApplicationJSONObject(UpdateOffice422ApplicationJSON updateOffice422ApplicationJSONObject) {
        this.updateOffice422ApplicationJSONObject = updateOffice422ApplicationJSONObject;
        return this;
    }
    
    public UpdateOfficeResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
