/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Contractify.ContractifyAPI.models.operations;

import Contractify.ContractifyAPI.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;


public class UpdateDocumentRequest {
    @SpeakeasyMetadata("request:mediaType=application/json")
    public Contractify.ContractifyAPI.models.shared.DocumentWrite documentWrite;

    public UpdateDocumentRequest withDocumentWrite(Contractify.ContractifyAPI.models.shared.DocumentWrite documentWrite) {
        this.documentWrite = documentWrite;
        return this;
    }
    
    /**
     * Id of the company
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=company")
    public Long company;

    public UpdateDocumentRequest withCompany(Long company) {
        this.company = company;
        return this;
    }
    
    /**
     * Id of the document
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=document")
    public Long document;

    public UpdateDocumentRequest withDocument(Long document) {
        this.document = document;
        return this;
    }
    
    public UpdateDocumentRequest(@JsonProperty("company") Long company, @JsonProperty("document") Long document) {
        this.company = company;
        this.document = document;
  }
}
