/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Contractify.ContractifyAPI.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class UpdateContractResponse {
    
    public String contentType;

    public UpdateContractResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public UpdateContractResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public UpdateContractResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * OK
     */
    
    public UpdateContract200ApplicationJSON updateContract200ApplicationJSONObject;

    public UpdateContractResponse withUpdateContract200ApplicationJSONObject(UpdateContract200ApplicationJSON updateContract200ApplicationJSONObject) {
        this.updateContract200ApplicationJSONObject = updateContract200ApplicationJSONObject;
        return this;
    }
    
    /**
     * Unauthenticated
     */
    
    public UpdateContract401ApplicationJSON updateContract401ApplicationJSONObject;

    public UpdateContractResponse withUpdateContract401ApplicationJSONObject(UpdateContract401ApplicationJSON updateContract401ApplicationJSONObject) {
        this.updateContract401ApplicationJSONObject = updateContract401ApplicationJSONObject;
        return this;
    }
    
    /**
     * Forbidden
     */
    
    public UpdateContract403ApplicationJSON updateContract403ApplicationJSONObject;

    public UpdateContractResponse withUpdateContract403ApplicationJSONObject(UpdateContract403ApplicationJSON updateContract403ApplicationJSONObject) {
        this.updateContract403ApplicationJSONObject = updateContract403ApplicationJSONObject;
        return this;
    }
    
    /**
     * Not Found
     */
    
    public UpdateContract404ApplicationJSON updateContract404ApplicationJSONObject;

    public UpdateContractResponse withUpdateContract404ApplicationJSONObject(UpdateContract404ApplicationJSON updateContract404ApplicationJSONObject) {
        this.updateContract404ApplicationJSONObject = updateContract404ApplicationJSONObject;
        return this;
    }
    
    /**
     * Invalid data posted
     */
    
    public UpdateContract422ApplicationJSON updateContract422ApplicationJSONObject;

    public UpdateContractResponse withUpdateContract422ApplicationJSONObject(UpdateContract422ApplicationJSON updateContract422ApplicationJSONObject) {
        this.updateContract422ApplicationJSONObject = updateContract422ApplicationJSONObject;
        return this;
    }
    
    public UpdateContractResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
