/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Contractify.ContractifyAPI.models.operations;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * UpdateRelation404ApplicationJSON - Not Found
 */

public class UpdateRelation404ApplicationJSON {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("message")
    public String message;

    public UpdateRelation404ApplicationJSON withMessage(String message) {
        this.message = message;
        return this;
    }
    
    public UpdateRelation404ApplicationJSON(){}
}
