/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Contractify.ContractifyAPI.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class UpdateDocumentResponse {
    
    public String contentType;

    public UpdateDocumentResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public UpdateDocumentResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public UpdateDocumentResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * OK
     */
    
    public UpdateDocument200ApplicationJSON updateDocument200ApplicationJSONObject;

    public UpdateDocumentResponse withUpdateDocument200ApplicationJSONObject(UpdateDocument200ApplicationJSON updateDocument200ApplicationJSONObject) {
        this.updateDocument200ApplicationJSONObject = updateDocument200ApplicationJSONObject;
        return this;
    }
    
    /**
     * Unauthenticated
     */
    
    public UpdateDocument401ApplicationJSON updateDocument401ApplicationJSONObject;

    public UpdateDocumentResponse withUpdateDocument401ApplicationJSONObject(UpdateDocument401ApplicationJSON updateDocument401ApplicationJSONObject) {
        this.updateDocument401ApplicationJSONObject = updateDocument401ApplicationJSONObject;
        return this;
    }
    
    /**
     * Forbidden
     */
    
    public UpdateDocument403ApplicationJSON updateDocument403ApplicationJSONObject;

    public UpdateDocumentResponse withUpdateDocument403ApplicationJSONObject(UpdateDocument403ApplicationJSON updateDocument403ApplicationJSONObject) {
        this.updateDocument403ApplicationJSONObject = updateDocument403ApplicationJSONObject;
        return this;
    }
    
    /**
     * Not Found
     */
    
    public UpdateDocument404ApplicationJSON updateDocument404ApplicationJSONObject;

    public UpdateDocumentResponse withUpdateDocument404ApplicationJSONObject(UpdateDocument404ApplicationJSON updateDocument404ApplicationJSONObject) {
        this.updateDocument404ApplicationJSONObject = updateDocument404ApplicationJSONObject;
        return this;
    }
    
    public UpdateDocumentResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
