/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Contractify.ContractifyAPI.models.operations;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * UpdateContract200ApplicationJSON - OK
 */

public class UpdateContract200ApplicationJSON {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("data")
    public Contractify.ContractifyAPI.models.shared.ContractRead data;

    public UpdateContract200ApplicationJSON withData(Contractify.ContractifyAPI.models.shared.ContractRead data) {
        this.data = data;
        return this;
    }
    
    public UpdateContract200ApplicationJSON(){}
}
