/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Contractify.ContractifyAPI.models.operations;

import Contractify.ContractifyAPI.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;


public class UpdateRelationRequest {
    @SpeakeasyMetadata("request:mediaType=application/json")
    public Contractify.ContractifyAPI.models.shared.RelationWrite relationWrite;

    public UpdateRelationRequest withRelationWrite(Contractify.ContractifyAPI.models.shared.RelationWrite relationWrite) {
        this.relationWrite = relationWrite;
        return this;
    }
    
    /**
     * Id of the company
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=company")
    public Long company;

    public UpdateRelationRequest withCompany(Long company) {
        this.company = company;
        return this;
    }
    
    /**
     * Id of the relation
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=relation")
    public Long relation;

    public UpdateRelationRequest withRelation(Long relation) {
        this.relation = relation;
        return this;
    }
    
    public UpdateRelationRequest(@JsonProperty("company") Long company, @JsonProperty("relation") Long relation) {
        this.company = company;
        this.relation = relation;
  }
}
