/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Contractify.ContractifyAPI.models.operations;

import Contractify.ContractifyAPI.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;


public class UpdateDepartmentRequest {
    @SpeakeasyMetadata("request:mediaType=application/json")
    public Contractify.ContractifyAPI.models.shared.DepartmentWrite departmentWrite;

    public UpdateDepartmentRequest withDepartmentWrite(Contractify.ContractifyAPI.models.shared.DepartmentWrite departmentWrite) {
        this.departmentWrite = departmentWrite;
        return this;
    }
    
    /**
     * Id of the company
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=company")
    public Long company;

    public UpdateDepartmentRequest withCompany(Long company) {
        this.company = company;
        return this;
    }
    
    /**
     * Id of the department
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=department")
    public Long department;

    public UpdateDepartmentRequest withDepartment(Long department) {
        this.department = department;
        return this;
    }
    
    public UpdateDepartmentRequest(@JsonProperty("company") Long company, @JsonProperty("department") Long department) {
        this.company = company;
        this.department = department;
  }
}
